# Generated by Django 6.0.4 on 2026-04-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_rename_doctors_doctor'),
        ('patients', '0002_rename_phone_no_patient_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appoinment_staatus',
            new_name='appointment_status',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appoinment_time',
            new_name='appointment_time',
        ),
    ]
