# Generated by Django 6.0.4 on 2026-04-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
